set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Tagbar'
Plugin 'octol/vim-cpp-enhanced-highlight'
call vundle#end()

filetype plugin indent on
set nu
set mouse=a
set laststatus=2
set incsearch
set ignorecase
set smartcase
set ruler
set hlsearch
set cursorline

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent
set autoindent

source $VIMRUNTIME/ftplugin/man.vim
nmap <Leader>man :Man 3 <cword><CR>
set t_Co=254

"Tagbar
let g:tagbar_left=1

