set nocompatible
filetyp off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'majutsushi/tagbar'
call vundle#end()
filetype plugin indent on

set number
syntax enable
syntax on "按照指定主题进行语法高亮
set laststatus=2 "设置状态栏
set tabstop=4 "tab长度
set smartindent "智能缩进
set autoindent "自动缩进
set cindent shiftwidth=4 "自动缩进为4个空格
set showmatch "显示括号匹配情况
set incsearch "即时查找
set hlsearch "高亮搜索结果
set mouse=a "开启鼠标
set cursorline
set expandtab "空格代替tab

"配色方案
"colorscheme torte
highlight Pmenu guibg=darkgrey guifg=black
highlight PmenuSel guibg=lightgrey guifg=black
